services:
  metastore:
    image: postgres:11
    hostname: metastore
    environment:
      POSTGRES_PASSWORD: hdfs
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      hadoopnet:
        ipv4_address: 172.28.1.1
    extra_hosts:
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  master:
    image: kalamangga/hadoop-master
    hostname: master
    depends_on:
      - metastore
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8020:8020"
      - "8080:8080"
      - "8088:8088"
      - "9870:9870"
      - "10000:10000"
    restart: always
    networks:
      hadoopnet:
        ipv4_address: 172.28.1.2
    extra_hosts:
      - "metastore:172.28.1.1"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  worker1:
    image: kalamangga/hadoop-worker
    hostname: worker1
    depends_on:
      - master
    ports:
      - "8042:8042"
      - "8081:8081"
      - "9864:9864"
    restart: always
    networks:
      hadoopnet:
        ipv4_address: 172.28.1.3
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  worker2:
    image: kalamangga/hadoop-worker
    hostname: worker2
    depends_on:
      - master
    ports:
      - "8043:8042"
      - "8082:8081"
      - "9865:9864"
    restart: always
    networks:
      hadoopnet:
        ipv4_address: 172.28.1.4
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "history:172.28.1.5"

volumes:
  namenode:
  namesecondary:
  datanode1:
  datanode2:
  metastore:

networks:
  hadoopnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
